name: FN_FAL113sMachinery
version: '${project.version}'
main: me.fnfal113.fn_falsmachinery.FN_FALSMachinery
api-version: 1.17
authors: [ FN_FAL113 ]
description: A custom addon for Slimefun that adds custom machines for production and ease of use
depend: [Slimefun]
website: https://github.com/FN-FAL113
